blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
    

]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('auth/', include("userauths.urls")),
    path('customer/', include("customer.urls")),
    path('vendor/', include("vendor.urls")),
    path('blog/', include("blog.urls")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='userauths/password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userauths/password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userauths/password/password_reset_confirmation.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password/password_reset_complete.html'), name='password_reset_complete'),


    path("ckeditor5/", include('django_ckeditor_5.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from userauths import models as userauths_models
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field
from django.utils import timezone

STATUS_CHOICES = [
    ('Draft', 'Draft'),
    ('Published', 'Published'),
]

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=150, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Blog(models.Model):
    image = models.ImageField(upload_to='blog_images', blank=True, null=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=350, unique=True, blank=True)
    author = models.ForeignKey(userauths_models.User, on_delete=models.CASCADE)
    content = CKEditor5Field(config_name='extends', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="Published")
    likes = models.ManyToManyField(userauths_models.User, blank=True, related_name="likes")
    views = models.PositiveIntegerField(default=0)
    is_featured = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def total_likes(self):
        return self.likes.all().count()

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    full_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    approved = models.BooleanField(default=False)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Comment by {self.full_name} on {self.blog.title}"

blog/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from blog import models as blog_models
from plugin.paginate_queryset import paginate_queryset
from django.contrib import messages

def blog_list(request):
    blogs_list = blog_models.Blog.objects.all().order_by('-date') 
    blogs = paginate_queryset(request, blogs_list, 10)

    context = {
        'blogs': blogs,
        'blogs_list': blogs_list,
    }
    return render(request, 'blog/blog_list.html', context)

def blog_detail(request, slug):
    blog = get_object_or_404(blog_models.Blog, slug=slug) 
    comments = blog.comments.filter(approved=True)  

    liked = False
    if blog.likes.filter(id=request.user.id).exists():
        liked = True

    context = {
        'blog': blog,
        'comments': comments,
        'liked': liked,
        'total_likes': blog.total_likes(),
    }
    return render(request, 'blog/blog_detail.html', context)

def create_comment(request, slug):
    blog = get_object_or_404(blog_models.Blog, slug=slug)
    if request.method == 'POST':
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        content = request.POST.get("content")

        blog_models.Comment.objects.create(
            blog=blog,
            full_name=full_name,
            email=email,
            content=content,
        )

    messages.success(request, "Comment created, awaiting moderation!")
    return redirect('blog:blog_detail', slug=blog.slug)

def like_blog(request):
    blog = get_object_or_404(blog_models.Blog, id=request.POST.get('blog_id'))
    if blog.likes.filter(id=request.user.id).exists():
        blog.likes.remove(request.user)
        liked = False
    else:
        blog.likes.add(request.user)
        liked = True
    
    context = {
        'total_likes': blog.total_likes(),
        'liked': liked,
    }

    if request.is_ajax():
        return JsonResponse(context)

    return redirect('blog_detail', slug=blog.slug)

templates/blog/blog_detail.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}

<main class="container">
  <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="d-flex flex-column justify-content-center align-items-center">
        <img src="{{blog.image.url}}" style="width: 100%; height: 400px; object-fit: cover; border-radius: 10px;" class="mb-5" alt="">
        <h1 class="display-4 fw-bold text-center">{{blog.title}}</h1>
    </div>
  </div>

  <div class="row g-5">
    <div class="col-md-12">

      <article class="blog-post">
        <p class="blog-post-meta mb-1 fs-6"><b>Date:</b> {{blog.date}}</p>
        <p class="blog-post-meta mb-1 fs-6"><b>Author:</b> {{blog.author.profile.full_name}}</p>
        <p class="blog-post-meta mb-1 fs-6"><b>Likes:</b> {{total_likes}} Likes</p>
        <hr>
        <p class="fs-4 blog-content">{{blog.content|safe}}</p>
      </article>
      <hr>
      <br>
      <div class="row">
        <div class="col-lg-6">
            <form action="{% url 'blog:create_comment' blog.slug %}" method="POST" class="row">
                {% csrf_token %}
                <div class="col-lg-12 mb-3">
                    <label for="" class="fw-semibold">Full Name</label>
                    <input type="text" class="form-control" name="full_name" placeholder="What's your full name?" id="">
                </div>
                <div class="col-lg-12 mb-3">
                    <label for="" class="fw-semibold">Email</label>
                    <input type="text" class="form-control" placeholder="Enter your email" name="email" id="">
                </div>
                <div class="col-lg-12 mb-3">
                    <label for="" class="fw-semibold">Comment</label>
                    <textarea name="content" class="form-control" id="" placeholder="Write comment"></textarea>
                </div>
                <div class="col-lg-12 mb-3">
                    <button type="submit" class="btn bg-primary text-white rounded btn-sm">Post Comment <i class="fas fa-paper-plane ms-2"></i></button>
                </div>
            </form>
        </div>
      </div>
      <br>
      <h2>Comments ({{comments.count}})</h2>
      <div class="row d-flex flex-column">
                
        
        {% for c in comments %}
            <div class="col-lg-4">
                <div class="bg-light p-3 m-2">
                    <h3>{{c.full_name}}</h3>
                    <p>{{c.content}}</p>
                </div>
            </div>
        {% endfor %}
        
        
      </div>
    </div>
  </div>

</main>

{% endblock content %}

templates/blog/blog_list.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}
    <section class="middle">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                    <div class="sec_title position-relative text-center">
                        <h1 class="ft-bold pt-3">Blog Articles ({{blogs_list.count}})</h1>
                    </div>
                </div>
            </div>
            <div class="row">
               
               {% for blog in blogs %}
                    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                        <div class="_blog_wrap shadow p-2 rounded">
                            <div class="_blog_thumb mb-2">
                                <a href="{% url 'blog:blog_detail' blog.slug %}" class="d-block">
                                    {% if blog.image %}
                                        <img src="{{blog.image.url}}" style="width: 100%; height: 200px; border-radius: 5px;" class="img-fluid rounded" alt="" />
                                    {% endif %}
                                </a>
                            </div>
                            <div class="_blog_caption">
                                <span class="text-muted mb-3">{{blog.date|date:"d M, Y"}}</span>
                                <h5 class="bl_title lh-1"><a href="{% url 'blog:blog_detail' blog.slug %}">{{blog.title|truncatechars:50}}</a></h5>
                                <p>{{blog.content|safe|truncatechars:150}}</p>
                                <a href="{% url 'blog:blog_detail' blog.slug %}" class="btn bg-primary text-white btn-sm rounded fs-sm">Read More <i class="fas fa-eye ms-1"></i></a>
                            </div>
                        </div>
                    </div>
               {% endfor %}
                
            </div>

            <nav>
                <ul class="pagination">
                    {% if blogs.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ blogs.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Previous</span>
                        </li>
                    {% endif %}

                    {% for num in blogs.paginator.page_range %}
                        <li class="page-item {% if blogs.number == num %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endfor %}

                    {% if blogs.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ blogs.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Next</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>
{% endblock content %}