blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    path("create_comment/<slug>/", views.create_comment, name="create_comment"),
    path("like_blog/", views.like_blog, name="like_blog"),
    

]

customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_wishlist, name="add_to_wishlist"),
    path("addresses/", views.addresses, name="addresses"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_address/<id>/", views.delete_address, name="delete_address"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('auth/', include("userauths.urls")),
    path('customer/', include("customer.urls")),
    path('vendor/', include("vendor.urls")),
    path('blog/', include("blog.urls")),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='userauths/password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='userauths/password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='userauths/password/password_reset_confirmation.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password/password_reset_complete.html'), name='password_reset_complete'),


    path("ckeditor5/", include('django_ckeditor_5.urls')),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.shop, name="shop"),
    path("category/<id>/", views.category, name="category"),
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("cart/", views.cart, name="cart"),
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),

    path("filter_products/", views.filter_products, name="filter_products"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),

    path('stripe_payment/<order_id>/', views.stripe_payment, name='stripe_payment'),
    path('stripe_payment_verify/<order_id>/', views.stripe_payment_verify, name='stripe_payment_verify'),
    #path('paypal_payment_verify/<order_id>/', views.paypal_payment_verify, name='paypal_payment_verify'),
    #path('razorpay_payment_verify/<order_id>/', views.razorpay_payment_verify, name='razorpay_payment_verify'),
    #path('paystack_payment_verify/<order_id>/', views.paystack_payment_verify, name='paystack_payment_verify'),
    #path('flutterwave_payment_callback/<order_id>/', views.flutterwave_payment_callback, name='flutterwave_payment_callback'),

    path("order_tracker_page/", views.order_tracker_page, name="order_tracker_page"),
    path("order_tracker_detail/<item_id>/", views.order_tracker_detail, name="order_tracker_detail"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_conditions/", views.terms_conditions, name="terms_conditions"),

]

userauths/urls.py
from django.urls import path

from userauths import views
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

store/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives, send_mail

from decimal import Decimal
import requests
import stripe
from plugin.service_fee import calculate_service_fee
#import razorpay

from plugin.paginate_queryset import paginate_queryset
from store import models as store_models
from customer import models as customer_models
from vendor import models as vendor_models
from userauths import models as userauths_models
from plugin.tax_calculation import tax_calculation
from plugin.exchange_rate import convert_usd_to_ron


stripe.api_key = settings.STRIPE_SECRET_KEY
#razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

def clear_cart_items(request):
    try:
        cart_id = request.session['cart_id']
        store_models.Cart.objects.filter(cart_id=cart_id).delete()
    except:
        pass
    return

def index(request):
    products = store_models.Product.objects.filter(status="Published")
    categories = store_models.Category.objects.all()
    
    context = {
        "products": products,
        "categories": categories,
    }
    return render(request, "store/index.html", context)

def shop(request):
    products_list = store_models.Product.objects.filter(status="Published")
    categories = store_models.Category.objects.all()
    colors = store_models.VariantItem.objects.filter(variant__name='Color').values('title', 'content').distinct()
    sizes = store_models.VariantItem.objects.filter(variant__name='Size').values('title', 'content').distinct()
    item_display = [
        {"id": "1", "value": 1},
        {"id": "2", "value": 2},
        {"id": "3", "value": 3},
        {"id": "40", "value": 40},
        {"id": "50", "value": 50},
        {"id": "100", "value": 100},
    ]

    ratings = [
        {"id": "1", "value": "★☆☆☆☆"},
        {"id": "2", "value": "★★☆☆☆"},
        {"id": "3", "value": "★★★☆☆"},
        {"id": "4", "value": "★★★★☆"},
        {"id": "5", "value": "★★★★★"},
    ]

    prices = [
        {"id": "lowest", "value": "De la cel mai mare la cel mai mic"},
        {"id": "highest", "value": "De la cel mai mic la cel mai mare"},
    ]


    print(sizes)

    products = paginate_queryset(request, products_list, 10)

    context = {
        "products": products,
        "products_list": products_list,
        "categories": categories,
         'colors': colors,
        'sizes': sizes,
        'item_display': item_display,
        'ratings': ratings,
        'prices': prices,
    }
    return render(request, "store/shop.html", context)

def category(request, id):
    category = store_models.Category.objects.get(id=id)
    products_list = store_models.Product.objects.filter(status="Published", category=category)

    query = request.GET.get("q")
    if query:
        products_list = products_list.filter(name__icontains=query)

    products = paginate_queryset(request, products_list, 10)

    context = {
        "products": products,
        "products_list": products_list,
        "category": category,
    }
    return render(request, "store/category.html", context)

def vendors(request):
    vendors = userauths_models.Profile.objects.filter(user_type="Vendor")
    
    context = {
        "vendors": vendors
    }
    return render(request, "store/vendors.html", context)

def product_detail(request, slug):
    product = store_models.Product.objects.get(status="Published", slug=slug)
    product_stock_range = range(1, product.stock + 1)

    related_products = store_models.Product.objects.filter(category=product.category).exclude(id=product.id)

    context = {
        "product": product,
        "product_stock_range": product_stock_range,
        "related_products": related_products,
    }
    return render(request, "store/product_detail.html", context)

def add_to_cart(request):
    # Get parameters from the request (ID, color, size, quantity, cart_id)
    id = request.GET.get("id")
    qty = request.GET.get("qty")
    color = request.GET.get("color")
    size = request.GET.get("size")
    cart_id = request.GET.get("cart_id")
    
    request.session['cart_id'] = cart_id

    # Validate required fields
    if not id or not qty or not cart_id:
        return JsonResponse({"error": "Nu ati selectat nicio culoare sau mărime"}, status=400)

    # Try to fetch the product, return an error if it doesn't exist
    try:
        product = store_models.Product.objects.get(status="Published", id=id)
    except store_models.Product.DoesNotExist:
        return JsonResponse({"error": "Produsul nu a fost găsit"}, status=404)

    # Check if the item is already in the cart
    existing_cart_item = store_models.Cart.objects.filter(cart_id=cart_id, product=product).first()

    # Check if quantity that user is adding exceed item stock qty
    if int(qty) > product.stock:
        return JsonResponse({"error": "Cantitatea depășește stocul curent"}, status=404)

    # If the item is not in the cart, create a new cart entry
    if not existing_cart_item:
        cart = store_models.Cart()
        cart.product = product
        cart.qty = qty
        cart.price = product.price
        cart.color = color
        cart.size = size
        cart.sub_total = Decimal(product.price) * Decimal(qty)
        cart.shipping = Decimal(product.shipping) * Decimal(qty)
        cart.total = cart.sub_total + cart.shipping
        cart.user = request.user if request.user.is_authenticated else None
        cart.cart_id = cart_id
        cart.save()

        message = "Produsul a fost adăugat coș"
    else:
        # If the item exists in the cart, update the existing entry
        existing_cart_item.color = color
        existing_cart_item.size = size
        existing_cart_item.qty = qty
        existing_cart_item.price = product.price
        existing_cart_item.sub_total = Decimal(product.price) * Decimal(qty)
        existing_cart_item.shipping = Decimal(product.shipping) * Decimal(qty)
        existing_cart_item.total = existing_cart_item.sub_total +  existing_cart_item.shipping
        existing_cart_item.user = request.user if request.user.is_authenticated else None
        existing_cart_item.cart_id = cart_id
        existing_cart_item.save()

        message = "Coșul de cumpăraturi a fost actualizat"

    # Count the total number of items in the cart
    total_cart_items = store_models.Cart.objects.filter(cart_id=cart_id)
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']

    # Return the response with the cart update message and total cart items
    return JsonResponse({
        "message": message ,
        "total_cart_items": total_cart_items.count(),
        "cart_sub_total": "{:,.2f}".format(cart_sub_total),
        "item_sub_total": "{:,.2f}".format(existing_cart_item.sub_total) if existing_cart_item else "{:,.2f}".format(cart.sub_total) 
    })

def cart(request):
    if "cart_id" in request.session:
        cart_id = request.session['cart_id']
    else:
        cart_id = None

    items = store_models.Cart.objects.filter(cart_id=cart_id)
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']
    
    try:
        addresses = customer_models.Address.objects.filter(user=request.user)
    except:
        addresses = None

    if not items:
        messages.warning(request, "Niciun produs în coș")
        return redirect("store:index")

    context = {
        "items": items,
        "cart_sub_total": cart_sub_total,
        "addresses": addresses,
    }
    return render(request, "store/cart.html", context)

def delete_cart_item(request):
    id = request.GET.get("id")
    item_id = request.GET.get("item_id")
    cart_id = request.GET.get("cart_id")
    
    # Validate required fields
    if not id and not item_id and not cart_id:
        return JsonResponse({"error": "Produsul nu a fost găsit"}, status=400)

    try:
        product = store_models.Product.objects.get(status="Published", id=id)
    except store_models.Product.DoesNotExist:
        return JsonResponse({"error": "Produsul nu a fost găsit"}, status=404)

    # Check if the item is already in the cart
    item = store_models.Cart.objects.get(product=product, id=item_id)
    item.delete()

    # Count the total number of items in the cart
    total_cart_items = store_models.Cart.objects.filter(cart_id=cart_id)
    cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']

    return JsonResponse({
        "message": "Item deleted",
        "total_cart_items": total_cart_items.count(),
        "cart_sub_total": "{:,.2f}".format(cart_sub_total) if cart_sub_total else 0.00
    })

def create_order(request):
    if request.method == "POST":
        address_id = request.POST.get("address")
        if not address_id:
            messages.warning(request, "Selectează o adresă pentru a continua")
            return redirect("store:cart")
        
        address = customer_models.Address.objects.filter(user=request.user, id=address_id).first()

        if "cart_id" in request.session:
            cart_id = request.session['cart_id']
        else:
            cart_id = None

        items = store_models.Cart.objects.filter(cart_id=cart_id)
        cart_sub_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(sub_total = models.Sum("sub_total"))['sub_total']
        cart_shipping_total = store_models.Cart.objects.filter(cart_id=cart_id).aggregate(shipping = models.Sum("shipping"))['shipping']
        
        order = store_models.Order()

templates/store/cart.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="/shop.html">Shop</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Cart</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="sec_title position-relative text-center">
                    <h3 class="ft-bold pt-3">Coș de cumpăraturi</h3>
                </div>
            </div>
        </div>

        <form action="{% url 'store:create_order' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-9">
                    <h4 class="fw-bold p-3">Articole din coș</h4>
                    <div style="overflow-y: scroll; max-height: 650px; overflow-x: hidden" class="p-3">
                        {% for item in items %}
                            <div class="shadow rounded mb-3 item_div_{{item.id}}">
                                <div class="row d-flex align-items-center p-3">
                                    <div class="col-lg-4 d-flex gap-3">
                                        <img src="{{item.product.image.url}}" alt="" style="width: 100px; height: 100px; object-fit: cover" />
                                        <div class="p-2">
                                            <h5>{{item.product.name}}</h5>
                                            <p class="mb-0 mt-0">Preț: {{item.price|intcomma}} lei</p>
                                            <p class="mb-0 mt-0">Vânzător: {{item.product.vendor.profile.full_name}}</p>
                                        </div>
                                    </div> 
                                    <div class="col-lg-2">
                                        <h4 class="fs-3">{{ item.price|intcomma }} lei</h4>
                                    </div>
                                    <div class="col-lg-2 d-flex">
                                        <button type="button" class="btn bg-primary text-white btn-sm update_cart_qty" data-update_type="decrease" data-product_id="{{item.product.id}}" data-item_id="{{item.id}}">-</button>
                                        <input type="number" readonly class="form-control form-sm item-qty-{{item.id}}" value="{{item.qty}}" name="" id="" />
                                        <button type="button" class="btn bg-primary text-white btn-sm update_cart_qty" data-update_type="increase" data-product_id="{{item.product.id}}" data-item_id="{{item.id}}">+</button>
                                    </div>
                                    <div class="col-lg-2">
                                        <h4 class="fs-3 mb-0"><span class="item_sub_total_{{item.id}}">{{item.sub_total|intcomma}} lei</span></h4>
                                    </div>
                                    <div class="col-lg-2">
                                        <button type="button" class="btn bg-danger text-white btn-sm rounded delete_cart_item" data-item_id="{{item.id}}" data-product_id="{{item.product.id}}" ><i class="fas fa-trash"></i></button>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="p-3">
                    <h4 class="fw-bold mb-3">Detalii de livrare</h4>
                        {% if request.user.is_authenticated %}
                            
                            {% if addresses %}
                                <div class="row">
                                    {% for address in addresses %}
                                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                                            <div class="card-wrap border rounded mb-4">
                                                <div class="card-wrap-header px-3 py-2 br-bottom d-flex align-items-center justify-content-between">
                                                    <div class="card-heafder-flex">
                                                        <h4 class="fs-md ft-bold mb-1">Adresa de livrare <a href="{% url 'customer:address_detail' address.id %}"><i class="fas fa-edit"></i></a></h4>
                                                    </div>
                                                </div>
                                                <div class="card-wrap-body px-3 py-3">
                                                    <p class="mb-0"><span class="fw-bold">Numele Complet: </span>{{address.full_name}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Email: </span>{{address.email}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Telefon Mobil: </span>{{address.mobile}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Adresa: </span>{{address.address}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Oraș: </span> {{address.city}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Județ: </span> {{address.state}}</p>
                                                    <p class="mb-0"><span class="fw-bold">Țara: </span> {{address.country}}</p>
                                                    <div class="mt-3">
                                                        <input id="address{{address.id}}" value="{{address.id}}" class="radio-custom" name="address" type="radio">
                                                        <label for="address{{address.id}}" class="radio-custom-label">Selectează Adresa</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <p>Nicio adresă încă, <a href="{% url 'customer:address_create' %}" class="text-primary">creează o adresă nouă.</a></p>
                            {% endif %}
                                
                        {% else %}
                        <p><a href="{% url 'userauths:sign-in' %}?next={{request.path}}" class="text-primary">Autentifică-te </a> sau <a class="text-primary" href="{% url 'userauths:sign-up' %}?next={{request.path}}">creează un cont </a> pentru a continua  </p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="shadow rounded p-3">
                        <h4 class="fw-bold">Rezumatul comenzii</h4>

                        <div>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="fw-semibold fs-6">Sub-total</p>
                                <p class="fs-6"><span class="cart_sub_total">{{cart_sub_total|intcomma}} lei</span></p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="fw-semibold fs-6">Livrare</p>
                                <p class="fs-6">0.00 lei</p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="fw-semibold fs-6">Taxe</p>
                                <p class="fs-6">0.00 lei</p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-3">
                                <p class="fw-bold text-dark fs-5">Total</p>
                                <p class="fw-bold text-dark fs-5"><span class="cart_sub_total">{{cart_sub_total|intcomma}} lei</span></p>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-center w-100 mt-3">
                        {% if request.user.is_authenticated %}
                            <button type="submit" class="btn bg-primary rounded text-white w-100">Continuă către finalizarea comenzii <i class="fas fa-arrow-right ms-1"></i></button>
                        {% else %}
                            <div>
                                <a href="{% url 'userauths:sign-in' %}?next={{request.path}}" class="btn bg-primary rounded text-white w-100 mb-3">Autentifică-te pentru a continua <i class="fas fa-sign-in-alt ms-1"></i></a>
                                <a href="{% url 'userauths:sign-up' %}?next={{request.path}}" class="rounded w-100 mt-3">Creează un cont nou<i class="fas fa-user-plus ms-1"></i></a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

{% endblock content %}

templates/store/category.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% load humanize %} 
{% block content %}
	
	<section class="middle">
		<div class="container">
			<h2 class="fw-bold mb-5">{{category.title}} (<span class="product_count">{{ products_list.count }}</span>)</h2>
			<form class="mb-5 d-flex justify-content-between align-items-center gap-2">
				<input type="text" class="form-control rounded" placeholder="Caută Produse..." name="q" id="">
				<button type="submit" class="btn bg-primary text-white rounded "><i class="fas fa-search"></i></button>
			</form>
			<div class="row">
				<div class="col-lg-12"> 
					<div class="row align-items-center rows-products" id="products-list">						
						 
						 {% for p in products %}
							<div class="col-lg-3">
								<div class="product_grid card b-0  rounded-3 shadow m-2 p-2">
									<div class="card-body p-0">
										<div class="shop_thumb position-relative">
											<a class="card-img-top d-block overflow-hidden" href="{% url 'store:product_detail' p.slug %}"><img class="card-img-top" style="width: 100%; height: 230px; object-fit: cover;" src="{{p.image.url}}" alt="..." /></a>
										</div>
									</div>
									<div class="card-footer b-0 p-0 pt-2 bg-white d-flex align-items-start justify-content-between">
										<div class="text-left">
											<div class="text-left">
												<div class="elso_titl"><span class="small">{{p.category.title}}</span></div>
												<h5 class="fs-md mb-0 lh-1 mb-1"><a href="{% url 'store:product_detail' p.slug %}">{{p.name}}</a></h5>
												  <div class="star-rating align-items-center d-flex justify-content-left mb-2 p-0 mt-3">
													{% if not p.average_rating  %}
													<i class="fas fa-star text-warning"></i>
													{% elif p.average_rating > 0 and p.average_rating < 2 %}
													<i class="fas fa-star text-warning"></i>
													{% elif p.average_rating > 1 and p.average_rating < 3 %}
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													{% elif p.average_rating > 2 and p.average_rating < 4 %}
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													{% elif p.average_rating > 3 and p.average_rating < 5 %}
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													{% elif p.average_rating > 4 %}
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													<i class="fas fa-star text-warning"></i>
													{% endif %}
												</div>
												<div class="elis_rty"><span class="ft-bold text-dark fs-sm">{{p.price}} lei</span></div>
											</div>
											<div class="d-flex align-items-center gap-3">
												<button type="button" class="btn btn-sm bg-primary text-white rounded add_to_cart" data-id="{{p.id}}">Adaugă în coș<i class="fas fa-shopping-cart ms-2"></i></button>
												<a href="#" class="me-2 add_to_wishlist" data-product_id="{{p.id}}"><i class="fas fa-heart fs-4 text-dark"></i></a>
                                        		<input type="hidden" class="quantity" value="1" name="" id="">
											</div>
										</div>
									</div>
								</div>
							</div>
                        {% empty %}
                        <p>Niciun produs pentru această categorie</p>
						 {% endfor %}
							
					</div>
				</div>				
			</div>
		</div>
	</section>

{% endblock content %}

templates/store/order_tracker_page.html
{% extends 'partials/base.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="gray py-3">
    <div class="container">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Acasă</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'store:shop' %}">Magazin</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Urmărire comandă </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="middle" style="margin-bottom: 600px;">
    <div class="container">
        <div class="row justify-content-center">
            <form class="col-12 col-md-10 col-lg-12 col-xl-12 text-center" method="POST">
                {% csrf_token %}
                <div class="p-4 d-inline-flex align-items-center justify-content-center circle bg-light-primary text-success mx-auto mb-4"><i class="fas fa-truck fs-1"></i></div>
                <h2 class="mb-2 ft-bold">Urmărire comandă</h2>
                <div class="d-flex align-items-center justify-content-center">
                    <input type="text"  name="item_id" class="form-control rounded w-50" placeholder="Tracking Id or Item Id" id="">
                </div>
                <button type="submit" class="btn btn-sm rounded text-white bg-primary mt-3">Urmărește comanda <i class="fas fa-arrow-right ms-1"></i></button>
            </form>
        </div>
    </div>
</section>

{% endblock content %}